DB_project/bookstore/urls.py
from django.urls import path
from . import views

app_name = "bookstore"

urlpatterns = [
    path('test1/', views.test1, name='test1'),
    path('test2/', views.test2, name='test2'),
    ############################관리자#################################
    path('resedit/', views.reseditPage, name='resedit'),
    ############################회원가입#################################
    path('reg/', views.regPage, name='reg'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:User_id>/home/', views.homePage, name='home'),
    ############################주문####################################
    path('order/', views.orderPage, name='order'),
    path('orderPayment/', views.orderPaymentPage, name='orderPayment'),
    path('CPorder/', views.CPorderPage, name='CPorder'),
    path('orderReserves/', views.orderReservesPage, name='orderReserves'),
    path('orderdone/', views.orderdonePage, name='orderdone'),
    ############################장바구니#################################
    path('cart/', views.cartPage, name='cart'),
    path('<int:book_id>/mulcartadd/', views.mulcartaddPage, name='mulcartadd'),
    path('<int:book_id>/sincartadd/', views.sincartaddPage, name='sincartadd'),
    path('<int:book_id>/cartdel/', views.cartdelPage, name='cartdel'),
    ############################회원정보수정##############################
    path('userinfo/', views.User_info, name='userinfo'),
    path('orderinfo/', views.Order_info, name='orderinfo'),
    path('sdinfo/', views.SD_info, name='sdinfo'),
    path('<int:SD_id>/sdadd/', views.SD_add, name='sdadd'),
    path('cardinfo/', views.CARD_info, name='cardinfo'),
    path('<int:CARD_id>/cardadd/', views.CARD_add, name='cardadd'),
    ############################쿠폰####################################
    path('coupon/', views.couponPage, name='coupon'),    #회원수정->쿠폰
    path('<int:BookOrder_id>/couponselect/', views.couponselectPage, name='couponselect'),    #주문->쿠폰
    path('<int:BookOrder_id>/<int:CP_id>/cpcancel/', views.cpcancelPage, name="cpcancel"),     #쿠폰 선택 취소 페이지
    path('<int:BookOrder_id>/<int:CP_id>/couponDC/', views.CouponDCpage, name='couponDC'),    #쿠폰 할인 값 넣기
    ############################동서페이####################################
    path('DPref/', views.DP_ref, name='DPref'),    #동서페이 조회
    path('DPissue/', views.DP_issue, name='DPissue'),    #동서페이 발급
    path('DPcharge/', views.DP_charege, name='DPcharge'),    #동서페이 충전
    path('DPdel/', views.DP_del, name='DPdel'),    #동서페이 해지
]

DB_project/bookstore/templates/bookstore/CARTPage.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
    <title>cartPage</title>
</head>
<body>
    <h3 style="display:inline">{{User.User_name}}님 장바구니</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a></br>
    <a href="{% url 'bookstore:order' %}">구매하기</a></br></br></br>
    <p>총가격 : {{Book_total_price}}원</p>
    {% for i in BookSB_list %}
        <p style="display:inline">{{i.Book.Book_name}}</p><!--책이름-->
        <p style="display:inline">{{i.Book.Book_price}}원</p><!--책정가-->
        <a href="{% url 'bookstore:cartdel' i.Book.id%}">장바구니 지우기</a></br>
    {% endfor %}
</body>
</html>

DB_project/bookstore/templates/bookstore/CPPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CouponPage</title>
</head>
<body>
    <h3 style="display:inline">{{User.User_name}}님 쿠폰페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    {% for i in CP_list %}
        <p>{{i.CP_kind}}</p>
    {% endfor%}
</body>
</html>

DB_project/bookstore/templates/bookstore/CPselectPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CouponSelectPage</title>
</head>
<body>
    {% if mes %}
        <script>
            alert("{{ mes }}")
        </script>
    {% endif %}
    <h3 style="display:inline">{{User.User_name }}님 쿠폰사용페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a></br></br></br></br>
    <a href="{% url 'bookstore:CPorder' %}">주문내역으로 돌아가기</a></br></br>
    {% for i in CP_list %}
        {% if i.CP_state == 1 or BookOrder_list.CP_kind == i.CP_kind %}    <!--사용진행중인 쿠폰 -->
            {{i.CP_kind}} (선택됨)
            <a style="display:inline" href="{% url 'bookstore:cpcancel' BookOrder_list.id i.id %}">선택취소</a></br></br>
        {% else %}
            <a href="{% url 'bookstore:couponDC' BookOrder_list.id i.id %}">{{i.CP_kind}}</a></br></br>
        {% endif %}
    {% endfor %}
</body>
</html>

DB_project/bookstore/templates/bookstore/DP.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
    <title>userinfo_DP_Page</title>
</head>
<body>
    {% if mes %}
        <script>
            alert("{{ mes }}")
        </script>
    {% endif %}
    <h3 style="display:inline">{{User.User_name}}님 동서페이 페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a></br></br></br>

    <!--EnrollPage-->
    {% if Page == "EnrollPage" %}
        <p>{{User.User_name}}님은 현재 동서페이 사용자가 아닙니다.</p>
        <p style="display:inline">동서페이를 등록하시겠습니까?</p>
        <a href="{% url 'bookstore:DPissue' %}">등록</a>
        <a href="{% url 'bookstore:userinfo' %}">미등록</a>
    {% endif %}

    <!--ReferencePage-->
    {% if Page == "ReferencePage" %}
        <a href="{% url 'bookstore:DPcharge' %}">충전하기</a>
        <p>최근거래일 : {{DP_list.DP_TradingDate}}</p>
        <p>최근거래번호 : {{DP_list.DP_history}}</p>
        <p>---------------------------------------------------------</p>
        <p>잔액 : {{DP_list.DP_price}}</p>
        <p>충전금액 : {{DP_list.DP_ChargePrice}}</p>
        <p>최근사용금액 : {{DP_list.DP_UsedPrice}}</p></br>
        <h3><b>!!!!!!!!!!!!!동서페이 해지하기!!!!!!!!!!!!!</b></h3>
        <b>동서페이 해지할경우 남은금액은 신용카드로 환불됩니다.</b><br>
        <a href="{% url 'bookstore:DPdel' %}">해지하기</a>
    {% endif %}

    <!--CharegePage-->
    {% if Page == "ChargePage" %}
        <form action="{% url 'bookstore:DPcharge' %}" method="post">
        {% csrf_token %}
            충전 금액 : <input type="text" name="DP_ChargePrice">
            <input type="submit" name="Register"></br>
        </form>
    {% endif %}
</body>
</html>

DB_project/bookstore/templates/bookstore/ORDERPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OrderPage</title>
</head>
<body>
    {% if mes %}
        <script>
            alert("{{mes}}")
        </script>
    {% endif %}
    <h3 style="display:inline">{{User.User_name}}님 구매페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
    <a href="{% url 'bookstore:cart' %}">장바구니</a></br></br></br>

    <!--OrderlistPage-->
    {% if Page == "OrderlistPage" %}
        <p style="display:inline"><b>주문내역&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</b></p>
        <a href="{% url 'bookstore:orderPayment' %}">결제하기</a></br></br>

        <p>상품명 / 정가 / 적립금 / 수량 / 합계 / 할인가 / 쿠폰 </p>
        {% for i in BookOrder_list %}
            <p style="display:inline">{{i.Book.Book_name}} /</p><!--책이름-->
            <p style="display:inline">{{i.Book.Book_price}} /</p><!--책정가-->
            <p style="display:inline">{{i.BO_reserves}} /</p><!--책적립금-->
            <p style="display:inline">{{i.BO_count}} /</p><!--책수량-->
            <p style="display:inline">{{i.BO_price}} /</p><!--책할인가합계-->
            <p style="display:inline">{{i.BO_DC_price}} /</p><!--책할인가-->
            {% if i.CP_kind == "" %}
                <a href="{% url 'bookstore:couponselect' i.id%}"> 쿠폰 사용하기</a></br>
            {% else %}
                <a href="{% url 'bookstore:couponselect' i.id%}"> 쿠폰 사용하기</a>
                <p style="display:inline">({{i.CP_kind}}) /</p><!--책할인가--></br>
            {% endif %}
        {% endfor %}</br>
        <p>---------------------------------------------------------</p>
        {% if Order_list.Order_DC_totalprice == 0 %}
            <p>총 상품금액 : {{Order_list.Order_totalprice}}</p>
        {% else %}
            <p>총 상품금액 : {{Order_list.Order_DC_totalprice}}</p>
        {% endif %}
    {% endif %}

    <!--PaymentPage-->
    <!--추가해야될거-->
    <!--할인, 동서페이 정리할것-->
    <!--동서페이 안사용한 경우 UI상으로 안보이게하기-->
    {% if Page == "PaymentPage" %}
        <p style="display:inline"><b>주문내역&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</b></p>
        <a href="{% url 'bookstore:orderdone' %}">주문하기</a></br></br>

        <!-- 동서페이 있는 경우 -->
        {% if DP_list %}
            <!--할인 안받은 경우-->
            {% if Order_list.Order_DC_totalprice == 0 %}
                <p>주문 금액 : {{Order_list.Order_totalprice}}</p>
                <!--동서페이 사용한 경우-->
                {% if Order_list.Order_DP != 0 %}
                    <p>동서페이 사용금액 : {{DP_list.DP_UsedPrice}}</p>
                    <b><p>결제 금액 : {{Order_list.Order_DP}}</p></b>
                <!--동서페이 안사용한 경우-->
                {% else %}
                    <p>동서페이 사용금액 : 0</p>
                    <b><p>결제 금액 : {{Order_list.Order_totalprice}}</p></b>
                {% endif %}
            <!--할인 받은 경우-->
            {% else %}
                <p>주문 금액 : {{Order_list.Order_DC_totalprice}}</p>
                <!--동서페이 사용한 경우-->
                {% if Order_list.Order_DP != 0 %}
                    <p>동서페이 사용금액 : {{DP_list.DP_UsedPrice}}</p>
                    <b><p>결제 금액 : {{Order_list.Order_DP}}</p></b>
                <!--동서페이 안사용한 경우-->
                {% else %}
                    <p>동서페이 사용금액 : 0</p>
                    <b><p>결제 금액 : {{Order_list.Order_DC_totalprice}}</p></b>
                {% endif %}
            {% endif %}

        <!-- 동서페이 없는 경우 -->
        {% else %}
            <!--할인 안받은 경우-->
            {% if Order_list.Order_DC_totalprice == 0 %}
                <p>주문 금액 : {{Order_list.Order_totalprice}}</p>
                <p>결제 금액 : {{Order_list.Order_totalprice}}</p>
            <!--할인 받은 경우-->
            {% else %}
                <p>주문 금액 : {{Order_list.Order_DC_totalprice}}</p>
                <p>결제 금액 : {{Order_list.Order_DC_totalprice}}</p>
            {% endif %}

        {% endif %}
        <p>주문일자 : {{Order_list.Order_date}}</p>

        <!-- 동서페이 발급된 경우-->
        {% if DP_list %}
        <p>---------------------------------------------------------</p>
        <h4 style="display:inline">동서페이</h4>
            {% if Order_list.Order_DP == 0 %}
                <form action="{% url 'bookstore:orderPayment' %}" method="post">
                {% csrf_token %}
                    사용금액 : <input type="text" name="DP_UsedPrice">
                    <input type="submit" name="Register"></br>
                </form>
                <p>동서페이 잔액 : {{DP_list.DP_price}}</p>
            {% else %}
                <p>동서페이 사용금액 : {{DP_list.DP_UsedPrice}}</p>
                <p>남은 잔액 : {{DP_list.DP_price}}</p>
            {% endif %}
        {% endif %}
        <p>---------------------------------------------------------</p>
        <h4 style="display:inline">적립금</h4>
            {% if Order_list.Order_used_Reserves == 0 %}
                <form action="{% url 'bookstore:orderReserves' %}" method="post">
                {% csrf_token %}
                    <p>보유 적립금 : {{User.User_Reserves}}</p>
                    사용적립금 : <input type="text" name="Order_used_Reserves">
                    <input type="submit" name="Register"></br>
                </form>
            {% else %}
                <p>보유 적립금 : {{User.User_Reserves}}</p>
                <p>적립금 사용금액 : {{Order_list.Order_used_Reserves}}</p>
            {% endif %}
        <p>---------------------------------------------------------</p>
        <h4 style="display:inline">결재카드</h4>
        <p>신용카드 종류 : {{Card_list.Card_name}}</p>
        <p>신용카드 번호 : {{Card_list.Card_num}}</p>
        <p>신용카드 유효기간 : {{Card_list.Card_date}}</p>
        <p>---------------------------------------------------------</p>
        <h4 style="display:inline">결재배송지</h4>
        <p>배송지 우편번호 : {{SD_list.SD_num}}</p>
        <p>배송지 기본주소 : {{SD_list.SD_ba}}</p>
        <p>배송지 상세주소 : {{SD_list.SD_da}}</p>
    {% endif %}

    <!--OrderDonePage-->
    {% if Page == "OrderDonePage" %}
        <p>주문이 완료되었습니다.</p>
        <p>적립된 적립금 : {{Order_list.Order_Reserves}}</p>
    {% endif %}
</body>
</html>

DB_project/bookstore/templates/bookstore/REGPage.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="content-Type" content="text/html"; charset="UTF-8">
    <title>회원가입</title>
</head>
<body>
    <h3 style="display:inline">회원가입</h3>
    <a href="{% url 'bookstore:login' %}">이전페이지</a>
    {% if mes %}
        <script>
        alert("{{ mes }}")
        </script>
    {% endif %}
    <form action="{% url 'bookstore:reg' %}" method="post">
    {% csrf_token %}
        이름 : <input type="text" name="name"></br>
        아이디 : <input type="text" name="id"></br>
        패스워드 : <input type="password" name="pw"></br>
        패스워드확인 : <input type="password" name="re_pw"></br>
        <p>주소 입력</p>
        우편번호 : <input type="text" name="sd_num"></br>
        기본주소 : <input type="text" name="sd_ba"></br>
        상세주소 : <input type="text" name="sd_da"></br>
        <p>카드 입력</p>
        카드 이름 : <input type="text" name="card_name"></br>
        카드 번호 : <input type="text" name="card_num"></br>
        카드 유효기간 : <input type="text" name="card_date"></br>
        <input type="submit" name="Register"></br>
    </form>
</body>
</html>

DB_project/bookstore/templates/bookstore/USERinfoPage.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
    <title>userPage</title>
</head>
<body>
    {% if mes %}
        <script>
            alert("{{ mes }}")
        </script>
    {% endif %}

    <!--InfoPage-->
    {% if Page == "InfoPage" %}
        <h3 style="display:inline">{{User.User_name}}님 회원수정</h3>
        <a href="{% url 'bookstore:login' %}">로그아웃</a>
        <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
        <a href="{% url 'bookstore:coupon' %}">내쿠폰 보기</a>
        <a href="{% url 'bookstore:DPref' %}">동서페이 보기</a></br></br></br>
        <form action="{% url 'bookstore:userinfo' %}" method="post">
        {% csrf_token %}
            이름 : <input type="text" value="{{User.User_name}}" name="name"></br>
            아이디 : <input type="text" value="{{User.User_id}}" name="id"></br>
            패스워드 : <input type="password" value="{{User.User_pw}}" name="pw"></br>
            <input type="submit" name="Register"></br>
        </form>
        <p>---------------------------------------------------------</p>
        <a href="{% url 'bookstore:resedit' %}">적립금 수정하기</a>
        <p>---------------------------------------------------------</p>
        <p>보유 적립금 : {{User.User_Reserves}}</p>
        <p>---------------------------------------------------------</p>
        {% for i in SD_list %}
            {% if i.id == User.Select_SD_id %}
                <p>기본 주소 : {{i.SD_ba}}{{i.SD_da}}</p>
            {% endif %}
        {% endfor %}
        <a href="{% url 'bookstore:sdinfo' %}">주소 추가/수정</a></br>
        <p>---------------------------------------------------------</p>
        {% for i in Card_list %}
            {% if i.id == User.Select_Card_id %}
                <p>기본 카드 : {{i.Card_name}}</p>
            {% endif %}
        {% endfor %}
        <a href="{% url 'bookstore:cardinfo' %}">카드 추가/수정</a></br>
        <p>---------------------------------------------------------</p>
        <p>최근 주문내역</p>
        <p>주문 번호 : {{Order_list.id}}</p>
        <p>주문 일자 : {{Order_list.Order_date}}</p>
        {% if Order_list.Order_DC_totalprice != 0 %}
            <p>주문 금액 : {{Order_list.Order_DC_totalprice}}</p></br>
        {% else %}
            <p>주문 금액 : {{Order_list.Order_totalprice}}</p></br>
        {% endif %}
        <a href="{% url 'bookstore:orderinfo' %}">주문내역 상세조회</a>
    {% endif %}

    <!--OrderInfoPage-->
    {% if Page == "OrderInfoPage" %}
        <h3 style="display:inline">{{User.User_name}}님 회원수정</h3>
        <a href="{% url 'bookstore:login' %}">로그아웃</a>
        <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
        <a href="{% url 'bookstore:home' User.id %}">홈으로</a></br></br></br>
        <b>주문내역</b></br>
        {% for i in Order_list %}
            <p>주문 번호 : {{i.id}}</p>
            <p>주문 일자 : {{i.Order_date}}</p>
            {% if i.Order_DC_totalprice != 0 %}
                <p>주문 금액 : {{i.Order_DC_totalprice}}</p>
            {% else %}
                <p>주문 금액 : {{i.Order_totalprice}}</p>
            {% endif %}
            <p>---------------------------------------------------------</p>
        {% endfor %}
    {% endif %}

    <!--SDPage-->
    {% if Page == "SDPage" %}
        <h3 style="display:inline">{{User.User_name}}님 주소수정 페이지</h3>
        <a href="{% url 'bookstore:login' %}">로그아웃</a>
        <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
        <a href="{% url 'bookstore:home' User.id %}">홈으로</a></br></br>
        <p>주소 추가</p>
        <form action="{% url 'bookstore:sdinfo' %}" method="post">
        {% csrf_token %}
            우편번호 : <input type="text" value="{{SD_list.SD_num}}" name="sd_num"></br>
            기본주소 : <input type="text" value="{{SD_list.SD_ba}}" name="sd_ba"></br>
            상세주소 : <input type="text" value="{{SD_list.SD_da}}" name="sd_da"></br>
            <input type="submit" name="Register"></br>
        </form>
        <p>주소 보기</p>
        {% for i in SD_list %}
            {% if i.id != User.Select_SD_id %}
                <a href="{% url 'bookstore:sdadd' i.id %}">기본배송지 선택</a></br></br>
            {% else %}
                <p>기본배송지</p>
            {% endif %}
            우편번호 : {{i.SD_num}}</br>
            기본주소 : {{i.SD_ba}}</br>
            상세주소 : {{i.SD_da}}</br></br>
            ---------------------------------------------------------</br>
        {% endfor %}
    {% endif %}

    <!--CardPage-->
    {% if Page == "CardPage" %}
        <h3 style="display:inline">{{User.User_name}}님 카드 수정 페이지</h3>
        <a href="{% url 'bookstore:login' %}">로그아웃</a>
        <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
        <a href="{% url 'bookstore:home' User.id %}">홈으로</a></br></br>
        <p>카드 추가</p>
        <form action="{% url 'bookstore:cardinfo' %}" method="post">
        {% csrf_token %}
            카드 이름 : <input type="text" value="{{Card_list.Card_name}}" name="card_name"></br>
            카드 번호 : <input type="text" value="{{Card_list.Card_num}}" name="card_num"></br>
            카드 유효기간 : <input type="text" value="{{Card_list.Card_date}}" name="card_date"></br>
            <input type="submit" name="Register"></br>
        </form>
        <p>카드 보기</p>
        {% for i in Card_list %}
            {% if i.id != User.Select_Card_id %}
                <a href="{% url 'bookstore:cardadd' i.id %}">기본카드 선택</a></br></br>
            {% else %}
                <p>기본카드</p>
            {% endif %}
            카드 이름 : {{i.Card_name}}</br>
            카드 번호 : {{i.Card_num}}</br>
            카드 유효기간 : {{i.Card_date}}</br>
            ---------------------------------------------------------</br>
        {% endfor %}
    {% endif %}
</body>
</html>

DB_project/bookstore/templates/bookstore/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>관리자 페이지</title>
</head>
<body>
    <h3 style="display:inline">admin님 적립금 수정 페이지</h3>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
    <a href="{% url 'bookstore:cart' %}">장바구니</a></br></br></br>
    {% if Page == "resedit" %}
        <form action="{% url 'bookstore:resedit' %}" method="post">
        {% csrf_token %}
            사용 적립금 : <input type="text" value="{{Book_list.Book_reserves}}" name="Book_reserves"></br>
            <input type="submit" name="Register"></br>
        </form>
        <p>현재 적립률 : {{Book_list.Book_reserves}}</p>
    {% endif %}
</body>
</html>

DB_project/bookstore/templates/bookstore/couponPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CouponPage</title>
</head>
<body>
    <h3 style="display:inline">{{User.User_name}}님 쿠폰페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    {% for i in CP_list %}
        <p>{{i.CP_kind}}</p>
    {% endfor%}
</body>
</html>

DB_project/bookstore/templates/bookstore/homePage.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
    <title>homePage</title>
</head>
<body>
    <h3 style="display:inline">도서구매사이트</h3>
    <p style="display:inline">{{User.User_name}}님 어서오세요.</p>
    <a href="{% url 'bookstore:logout' %}">로그아웃</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    <a href="{% url 'bookstore:cart' %}">장바구니</a></br></br></br>
    {% for i in Book_list %}
        <p style="display:inline"><b>{{i.Book_name}}</b></p>
        <p style="display:inline">(재고량 : {{i.Book_stock}})</p>
        <a href="{% url 'bookstore:mulcartadd' i.id %}">장바구니추가</a>
        <a href="{% url 'bookstore:sincartadd' i.id %}">바로구매</a></br>
    {% endfor %}
</body>
</html>

DB_project/bookstore/templates/bookstore/orderdonePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-Type" content="text/html"; charset="UTF-8">
    <title>주문완료페이지</title>
</head>
<body>
    <h3 style="display:inline">{{User.User_name}}님 구매페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a>
    <p>주문이 완료되었습니다.</p>
</body>
</html>

DB_project/bookstore/templates/bookstore/sdaddPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-Type" content="text/html"; charset="UTF-8">
    <title>SDaddPage</title>
</head>
<body>
    {% if mes %}
        <script>
            {{mes}}
        </script>
    {% endif %}
    <h3 style="display:inline">{{User.User_name}}님 주소수정 페이지</h3>
    <a href="{% url 'bookstore:login' %}">로그아웃</a>
    <a href="{% url 'bookstore:userinfo' %}">정보수정</a>
    <a href="{% url 'bookstore:home' User.id %}">홈으로</a></br></br>
    <p>주소 추가</p>
    <form action="{% url 'bookstore:sdadd' %}" method="post">
    {% csrf_token %}
        우편번호 : <input type="text" value="{{SD_list.SD_num}}" name="sd_num"></br>
        기본주소 : <input type="text" value="{{SD_list.SD_ba}}" name="sd_ba"></br>
        상세주소 : <input type="text" value="{{SD_list.SD_da}}" name="sd_da"></br>
        <input type="submit" name="Register"></br>
    </form>
    <p>주소 보기</p>
    {% for i in SD_list %}
        우편번호 : {{i.SD_num}}</br>
        기본주소 : {{i.SD_ba}}</br>
        상세주소 : {{i.SD_da}}</br></br>
    {% endfor %}
</body>
</html>

DB_project/bookstore/templates/bookstore/test1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'bookstore:test2' %}">test2로</a>
</body>
</html>

DB_project/bookstore/templates/bookstore/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    session전달받은값 : {{User}}
</body>
</html>